# This file exists to override the upstream v2/.dockerignore file without
# actually modifying upstream files
**

# Ignore everything except below
!/v2/go.mod
!/v2/go.sum
!/v2/vendor/**
!/v2/cmd/**
!/v2/pkg/**
!/v2/internal/**
!/v2/api/**
